; -----------------------------------------------------------------------------
;
;                           ZERO-PAGE variables
;
; -----------------------------------------------------------------------------

zp_00 = $00     ;
zp_01 = $01     ;
zp_02 = $02     ;
zp_03 = $03     ;
zp_04 = $04     ;
zp_05 = $05     ;
zp_06 = $06     ;
zp_07 = $07     ;
zp_08 = $08     ;
zp_09 = $09     ;
zp_0A = $0A     ;
zp_0B = $0B     ;
zp_0D = $0D     ;
zp_0F = $0F     ;

zp_12 = $12     ;
zp_13 = $13     ;
zp_14 = $14     ;
zp_15 = $15     ;
zp_16 = $16     ;
zp_17 = $17     ;
zp_18 = $18     ;
zp_1A = $1A     ;
zp_1B = $1B     ;
zp_1C = $1C     ;
zp_1E = $1E     ;

zp_20 = $20     ;
zp_22 = $22     ;
zp_23 = $23     ;
zp_24 = $24     ;
zp_25 = $25     ;
zp_28 = $28     ;
zp_2A = $2A     ;
zp_2B = $2B     ;
zp_2D = $2D     ;
zp_2E = $2E     ;
zp_2F = $2F     ;

zp_34 = $34     ;
zp_35 = $35     ;
zp_3B = $3B     ;
zp_3C = $3C     ;
zp_3D = $3D     ;
zp_3E = $3E     ;

zp_40 = $40     ;
zp_43 = $43     ;
zp_44 = $44     ;
zp_45 = $45     ;
zp_46 = $46     ;
zp_47 = $47     ;
zp_48 = $48     ;
zp_49 = $49     ;
zp_4A = $4A     ;
zp_4B = $4B     ;
zp_4C = $4C     ;
zp_4D = $4D     ;
zp_4E = $4E     ;
zp_4F = $4F     ;

zp_50 = $50     ;
zp_51 = $51     ;
zp_52 = $52     ;
zp_53 = $53     ;
zp_54 = $54     ;
zp_55 = $55     ;
zp_56 = $56     ;
zp_57 = $57     ;
zp_58 = $58     ;
zp_59 = $59     ;
zp_5A = $5A     ;
zp_5B = $5B     ;
zp_5C = $5C     ;
zp_5D = $5D     ;
zp_5E = $5E     ;
zp_5F = $5F     ;

zp_60 = $60     ;
zp_61 = $61     ;
zp_62 = $62     ;
zp_63 = $63     ;
zp_64 = $64     ;
zp_65 = $65     ;
zp_66 = $66     ;

zp_7A = $7A     ;
zp_7B = $7B     ;
zp_7C = $7C     ;
zp_7F = $7F     ;

zp_80 = $80     ;
zp_81 = $81     ;
zp_82 = $82     ;
zp_83 = $83     ;
zp_84 = $84     ;
zp_85 = $85     ;
zp_86 = $86     ;
zp_87 = $87     ;
zp_88 = $88     ;
zp_89 = $89     ;
zp_8A = $8A     ;
zp_8B = $8B     ;
zp_8C = $8C     ;
zp_8D = $8D     ;
zp_8E = $8E     ;
zp_8F = $8F     ;

zp_90 = $90     ;
zp_91 = $91     ;
zp_92 = $92     ;
zp_94 = $94     ;
zp_96 = $96     ;
zp_97 = $97     ;
zp_99 = $99     ;
zp_9A = $9A     ;
zp_9B = $9B     ;
zp_9C = $9C     ;
zp_9D = $9D     ;
zp_9E = $9E     ;
zp_9F = $9F     ;

zp_A0 = $A0     ;
zp_A1 = $A1     ;
zp_A2 = $A2     ;
zp_A3 = $A3     ;
zp_A4 = $A4     ;
zp_A5 = $A5     ;
zp_A6 = $A6     ;
zp_A7 = $A7     ;
zp_A8 = $A8     ;
zp_A9 = $A9     ;
zp_AD = $AD     ;

zp_BD = $BD     ;

zp_D1 = $D1     ;

zp_E5 = $E5     ;
zp_E6 = $E6     ;
zp_E7 = $E7     ;
zp_E9 = $E9     ;
zp_EB = $EB     ;
zp_ED = $ED     ;

zp_EF = $EF     ;

zp_F0 = $F0     ;
zp_F1 = $F1     ;
zp_F2 = $F2     ;
zp_F3 = $F3     ;
zp_F4 = $F4     ;
zp_F5 = $F5     ;
zp_F6 = $F6     ;
zp_F7 = $F7     ;
zp_FC = $FC     ;
zp_FD = $FD     ;
zp_FE = $FE     ;
zp_FF = $FF     ;


; -----------------------------------------------------------------------------
;
;                           System RAM variables
;
; -----------------------------------------------------------------------------

ram_0100 = $0100    ;

ram_0200 = $0200    ;
ram_0220 = $0220    ;
ram_0240 = $0240    ;
ram_0260 = $0260    ;
ram_0280 = $0280    ;
ram_02A0 = $02A0    ;
ram_02C0 = $02C0    ;
ram_02E0 = $02E0    ;

ram_0300 = $0300    ;
ram_0301 = $0301    ;
ram_0302 = $0302    ;
ram_0303 = $0303    ;
ram_0304 = $0304    ;
ram_0305 = $0305    ;
ram_0306 = $0306    ;
ram_0307 = $0307    ;
ram_0308 = $0308    ;
ram_0309 = $0309    ;
ram_030A = $030A    ;
ram_030B = $030B    ;
ram_030C = $030C    ;
ram_030D = $030D    ;
ram_030E = $030E    ;
ram_030F = $030F    ;
ram_0310 = $0310    ;
ram_0311 = $0311    ;
ram_0312 = $0312    ;
ram_0313 = $0313    ;
ram_0320 = $0320    ;
ram_0340 = $0340    ;
ram_0360 = $0360    ;
ram_0370 = $0370    ;
ram_0371 = $0371    ;
ram_0372 = $0372    ;
ram_0373 = $0373    ;
ram_0374 = $0374    ;
ram_0376 = $0376    ;
ram_0377 = $0377    ;
ram_037A = $037A    ;
ram_0378 = $0378    ;
ram_037B = $037B    ;
ram_037C = $037C    ;
ram_037E = $037E    ;
ram_037F = $037F    ;
ram_0380 = $0380    ;
ram_03A0 = $03A0    ;
ram_03C0 = $03C0    ;
ram_03E0 = $03E0    ;

ram_0400 = $0400    ;
ram_0401 = $0401    ;
ram_0402 = $0402    ;
ram_0403 = $0403    ;
ram_0404 = $0404    ;
ram_0405 = $0405    ;
ram_0409 = $0409    ;
ram_040A = $040A    ;
ram_040B = $040B    ;
ram_040C = $040C    ;
ram_040D = $040D    ;
ram_040E = $040E    ;
ram_040F = $040F    ;
ram_0410 = $0410    ;
ram_0411 = $0411    ;
ram_0414 = $0414    ;
ram_0416 = $0416    ;
ram_0418 = $0418    ;
ram_0419 = $0419    ;
ram_041F = $041F    ;
ram_0421 = $0421    ;
ram_041A = $041A    ;
ram_041C = $041C    ;
ram_0422 = $0422    ;
ram_0423 = $0423    ;
ram_0424 = $0424    ;
ram_0425 = $0425    ;
ram_0429 = $0429    ;
ram_042A = $042A    ;
ram_042C = $042C    ;
ram_042D = $042D    ;
ram_0435 = $0435    ;
ram_0436 = $0436    ;
ram_0438 = $0438    ;
ram_043D = $043D    ;
ram_043E = $043E    ;
ram_043F = $043F    ;
ram_0440 = $0440    ;

ram_0600 = $0600    ;
ram_0601 = $0601    ;
ram_0602 = $0602    ;
ram_0603 = $0603    ;
ram_0604 = $0604    ;
ram_063E = $063E    ;
ram_063F = $063F    ;
ram_0640 = $0640    ;
ram_066D = $066D    ;
ram_066E = $066E    ;
ram_0672 = $0672    ;
ram_0673 = $0673    ;
ram_0674 = $0674    ;
ram_0675 = $0675    ;
ram_0678 = $0678    ;
ram_0679 = $0679    ;
ram_067B = $067B    ;
ram_067C = $067C    ;
ram_067D = $067D    ;
ram_067E = $067E    ;
ram_067F = $067F    ;
ram_0680 = $0680    ;
ram_0681 = $0681    ;
ram_0682 = $0682    ;
ram_06C0 = $06C0    ;
ram_06C3 = $06C3    ;
ram_06C6 = $06C6    ;
ram_06CD = $06CD    ;

ram_0700 = $0700    ;
ram_0701 = $0701    ;
ram_0709 = $0709    ;
ram_070A = $070A    ;
ram_070B = $070B    ;
ram_070C = $070C    ;
ram_070D = $070D    ;
ram_0710 = $0710    ;
ram_0715 = $0715    ;
ram_0716 = $0716    ;
ram_071F = $071F    ;
ram_0720 = $0720    ;
ram_0729 = $0729    ;
ram_072A = $072A    ;
ram_0733 = $0733    ;
ram_0734 = $0734    ;
ram_0739 = $0739    ;
ram_073A = $073A    ;
ram_0743 = $0743    ;
ram_0744 = $0744    ;
ram_074D = $074D    ;
ram_074E = $074E    ;
ram_0757 = $0757    ;
ram_075C = $075C    ;
ram_0761 = $0761    ;
ram_0762 = $0762    ;
ram_076B = $076B    ;
ram_076D = $076D    ;
ram_076F = $076F    ;
ram_0770 = $0770    ;
ram_0773 = $0773    ;
ram_0777 = $0777    ;
ram_077B = $077B    ;
ram_077C = $077C    ;
ram_079F = $079F    ;
ram_07A0 = $07A0    ;
ram_07A1 = $07A1    ;
ram_07A2 = $07A2    ;
ram_07A3 = $07A3    ;
ram_07A4 = $07A4    ;
ram_07A5 = $07A5    ;
ram_07A6 = $07A6    ;
ram_07D2 = $07D2    ;
ram_07E3 = $07E3    ;
ram_07ED = $07ED    ;


; -----------------------------------------------------------------------------
;
;                           I/O Mapped Registers
;
; -----------------------------------------------------------------------------

PpuControl_2000  = $2000    ;
PpuMask_2001     = $2001    ;
PpuStatus_2002   = $2002    ;

OamAddr_2003     = $2003    ;
OamData_2004     = $2004    ;

PpuScroll_2005   = $2005    ;
PpuAddr_2006     = $2006    ;
PpuData_2007     = $2007    ;

;DDLC VVVV
;Duty (D), envelope loop / length counter halt (L), constant volume (C), volume/envelope (V)
Sq0Duty_4000     = $4000    ;
;EPPP NSSS
;Sweep unit: enabled (E), period (P), negate (N), shift (S)
Sq0Sweep_4001    = $4001    ;
;TTTT TTTT
;Timer low (T)
Sq0Timer_4002    = $4002    ;
;LLLL LTTT
;Length counter load (L), timer high (T)
Sq0Length_4003   = $4003    ;
;DDLC VVVV
;Duty (D), envelope loop / length counter halt (L), constant volume (C), volume/envelope (V)
Sq1Duty_4004     = $4004    ;
;EPPP NSSS
;Sweep unit: enabled (E), period (P), negate (N), shift (S)
Sq1Sweep_4005    = $4005    ;
;TTTT TTTT
;Timer low (T)
Sq1Timer_4006    = $4006    ;
;LLLL LTTT
;Length counter load (L), timer high (T)
Sq1Length_4007   = $4007    ;
;CRRR RRRR
;Length counter halt / linear counter control (C), linear counter load (R)
TrgLinear_4008   = $4008    ;
;TTTT TTTT
;Timer low (T)
TrgTimer_400A    = $400A    ;
;LLLL LTTT
;Length counter load (L), timer high (T)
TrgLength_400B   = $400B    ;
;--LC VVVV
;Envelope loop / length counter halt (L), constant volume (C), volume/envelope (V)
NoiseVolume_400C = $400C    ;
;L--- PPPP
;Loop noise (L), noise period (P)
NoisePeriod_400E = $400E    ;
;LLLL L---
;Length counter load (L)
NoiseLength_400F = $400F    ;
;IL-- RRRR
;IRQ enable (I), loop (L), frequency (R)
DmcFreq_4010     = $4010    ;
;-DDD DDDD
;Load counter (D)
DmcCounter_4011  = $4011    ;
;AAAA AAAA
;Sample address (A)
DmcAddress_4012  = $4012    ;
;LLLL LLLL
;Sample length (L)
DmcLength_4013   = $4013    ;

SpriteDma_4014   = $4014    ;

;Read:
;IF-D NT21
;DMC interrupt (I), frame interrupt (F), DMC active (D), length counter > 0 (N/T/2/1)
;
;Write:
;---D NT21
;Enable DMC (D), noise (N), triangle (T), and pulse channels (2/1)
ApuStatus_4015   = $4015    ;

Ctrl1_4016       = $4016    ;
Ctrl2_FrameCtr_4017 = $4017 ;


; -----------------------------------------------------------------------------
;
;                               MMC3 registers
;
; -----------------------------------------------------------------------------

mmc3_bank_select = $8000    ;
mmc3_bank_data = $8001      ;
mmc3_mirroring = $A000      ;
mmc3_ram_protect = $A001    ;

mmc3_irq_latch = $C000      ;
mmc3_irq_reload = $C001     ;

mmc3_irq_disable = $E000    ;
mmc3_irq_enable = $E001     ;
